### PR TITLE
[IOS-4190] Adding native ad implementation.

### PR DESCRIPTION
**Pull request by stanley-vungle**
Native Ad implementation.

Testing ticket: IOS-4438

Endpoint: QA
AppID: 61444db7823f8fe13f7964f0
Placement: NATIVETEST1-9380471
Header: X-Vungle-RTB-ID:5fd219d7c80cb9051249a6ab

The native ad unit ID to be set in AdUnit.m: ca-app-pub-6614121354918432/5577154998
The GAID to be set in the Info.plist is: ca-app-pub-6614121354918432~3362695820

To test:
- Set endpoint to QA and build locally. 
- Use Charles to add the RTB header.
- Enable and accept ATT or use the iOS Simulator.

### CODE REVIEW

**Comment by ashinagawa** [comment]
@stanley-vungle got few questions:

`Header: X-Vungle-RTB-ID:5fd219d7c80cb9051249a6ab`
This should be added for ad request from Vungle SDK?

`AppID: 61444db7823f8fe13f7964f0`
`Placement: NATIVETEST1-9380471`
These are linked to AdMob AdUnit on their dashboard, right? Do we need to map/rewrite through Charles?

`The native ad unit ID to be set in AdUnit.m: ca-app-pub-6614121354918432/5577154998`
`The GAID to be set in the Info.plist is: ca-app-pub-6614121354918432~3362695820`
Why you don't add this to `VungleRewardBasedVideo (= AdMob QA Test App)` ?

**Comment by stanley-vungle** [comment]
> This should be added for ad request from Vungle SDK?
Yes. Set that to the /ads requests like testing native ads on the native SDK

> These are linked to AdMob AdUnit on their dashboard, right? Do we need to map/rewrite through Charles?
Yes. This is linked on their dashboard. No need for Charles. You need to change the GAID and the Ad unit to the one provided because native ad isn't on prod app id so it is configured to a different app.

> Why you don't add this to VungleRewardBasedVideo (= AdMob QA Test App) ?
Because those ids are configured just for native ads for the QA endpoint. If I push it to the github repo, then all other ad units will not work.

**Review by ashinagawa — APPROVED** [review]
LGTM.

Verified that Native ads for AdMob worked properly.

**Review by ManojBudumuru-vungle — APPROVED** [review]
LGTM

**Pull request merged**
